version: '2.1'
services:
  postgresql:
    build: ./services/database
    environment:
      - PGDATA=/var/lib/postgresql/site
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
  redis:
    image: bitnami/redis:6.0.9
    environment: 
      - REDIS_PASSWORD=dev
  php-fpm:
    image: bitnami/php-fpm
    volumes:
      - ./services/php-fpm/php.conf:/opt/bitnami/php/etc/php-fpm.conf
      - ./services/php-fpm/www.conf:/opt/bitnami/php/etc/php-fpm.d/www.conf
      - ./services/php-fpm/www.conf:/opt/bitnami/php/etc/php-fpm.d/www.conf.default
      - ./services/php-fpm/php.ini:/opt/bitnami/php/etc/php.ini
      - ./services/php-fpm:/app
    environment:
      - REDIS_HOST=redis
      - DB_NAME=dev
      - DB_USER=dev
      - DB_PASS=dev
      - DB_HOST=postgresql
  nginx:
    image: openresty/openresty:xenial
    depends_on:
      - php-fpm
    volumes:
      - ./services/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    ports:
      - "127.0.0.1:${NGINX_EXTERNAL_PORT:-8990}:80"
    entrypoint: nginx
    command: -g "daemon off;"