replicaCount: 2

ingress:
  host: arch.homework
  
postgresql:
  enabled: true
  postgresqlUsername: dev
  postgresqlPassword: dev
  postgresqlDatabase: dev
  service:
    port: 5432
  initdbUser: "postgres"
  initdbScripts:
    db-init.sql: |
      CREATE EXTENSION if not exists pgcrypto;
      CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
  metrics:
    enabled: true
    service:
      type: NodePort
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
      loadBalancerIP:
    serviceMonitor:
      enabled: true
      additionalLabels: {}
      namespace: default
      interval: 15s
      scrapeTimeout: 10s    
      