{
 "title": "Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Nginx monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_requests[1m])",
     "legendFormat": "Requests per second"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, exported_endpoint) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\n) * 1000",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.9, \n      sum by (le, exported_endpoint) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\n) * 1000",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.95, \n      sum by (le, exported_endpoint) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\n) * 1000",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le, exported_endpoint) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\n) * 1000",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Errors total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_requests{status=\"500\"})",
     "legendFormat": "500"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=\"404\"}[1m]))",
     "legendFormat": "404"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=\"500\"}[1m]))",
     "legendFormat": "500"
    }
   ]
  },
  { "title": "App monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Current request latency distribution, ms",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, exported_endpoint) \n         (rate(avernusx_latency_bucket[1m]))\n) * 1000",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.9, \n      sum by (le, exported_endpoint) \n         (rate(avernusx_latency_bucket[1m]))\n) * 1000",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.95, \n      sum by (le, exported_endpoint) \n         (rate(avernusx_latency_bucket[1m]))\n) * 1000",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le, exported_endpoint) \n         (rate(avernusx_latency_bucket[1m]))\n) * 1000",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, exported_endpoint) \n         (rate(avernusx_latency_bucket[1m]))\n) * 1000",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.9, \n      sum by (le, exported_endpoint) \n         (rate(avernusx_latency_bucket[1m]))\n) * 1000",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.95, \n      sum by (le, exported_endpoint) \n         (rate(avernusx_latency_bucket[1m]))\n) * 1000",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le, exported_endpoint) \n         (rate(avernusx_latency_bucket[1m]))\n) * 1000",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(avernusx_error500[1m]))",
     "legendFormat": "500"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(avernusx_requests[30s]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Database monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true
  },
  {
   "title": "Queries per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{datname=\"dev\"}[1m])) + sum(irate(pg_stat_database_xact_rollback{datname=\"dev\"}[1m]))",
     "legendFormat": "Queries per second"
    }
   ]
  },
  {
   "title": "Rows",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched{datname=\"dev\"}[1m])",
     "legendFormat": "Rows fetched"
    },
    {
     "expr": "rate(pg_stat_database_tup_inserted{datname=\"dev\"}[1m])",
     "legendFormat": "Rows inserted"
    },
    {
     "expr": "rate(pg_stat_database_tup_updated{datname=\"dev\"}[1m])",
     "legendFormat": "Rows updated"
    },
    {
     "expr": "rate(pg_stat_database_tup_deleted{datname=\"dev\"}[1m])",
     "legendFormat": "Rows deleted"
    },
    {
     "expr": "rate(pg_stat_database_tup_returned{datname=\"dev\"}[1m])",
     "legendFormat": "Rows returned"
    }
   ]
  },
  { "title": "Pods monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "POD CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\", namespace=\"default\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "POD Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"POD\", namespace=\"default\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}