enabled: true
postgresqlUsername: dev
postgresqlPassword: dev
postgresqlDatabase: dev
service:
  port: 5432
initdbUser: "postgres"
initdbScripts:
  db-init.sql: |
    CREATE EXTENSION if not exists pgcrypto;
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";