apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-benchmark"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-benchmark"
    spec:
      restartPolicy: Never
      containers:
      - name: benchmark
        image: devth/alpine-bench:latest
        command:
          - sh
          - "-c"
          - |
            while true; 
              do echo "{\"id\":\"5fdd4041-7d73-4264-a422-ab667ebbde65\", \"login\": \"test$RANDOM\", \"email\": \"test$RANDOM\", \"password\": \"test$RANDOM\"}" > user.json;
              ab -n 10 -H 'Host: arch.homework' -T application/json -p ./user.json http://nginx-nginx-ingress-controller/otusapp/vlaznev/api/v1/users; 
              sleep 1; 
            done &
            while true; 
              do ab -n 1 -H 'Host: arch.homework' http://nginx-nginx-ingress-controller/otusapp/vlaznev/api/v1/users/5fdd4041-7d73-4264-a422-ab667ebbde65; 
              sleep 1; 
            done &
            while true; 
              do echo "{\"login\": \"test$RANDOM\", \"email\": \"test$RANDOM\", \"password\": \"test$RANDOM\"}" > user.json;
              ab -n 1 -H 'Host: arch.homework' -T application/json -u ./user.json http://nginx-nginx-ingress-controller/otusapp/vlaznev/api/v1/users/5fdd4041-7d73-4264-a422-ab667ebbde65; 
              sleep 1; 
            done &
            while true; 
              do ab -n 1 -H 'Host: arch.homework' -m DELETE http://nginx-nginx-ingress-controller/otusapp/vlaznev/api/v1/users/5fdd4041-7d73-4264-a422-ab667ebbde65; 
              sleep 1; 
            done &
            while true; 
              do ab -n 10 -H 'Host: arch.homework' http://nginx-nginx-ingress-controller/otusapp/vlaznev/api/v1/users; 
              sleep 1; 
            done &
            while true; 
              do ab -n 10 -H 'Host: arch.homework' http://nginx-nginx-ingress-controller/otusapp/vlaznev/error500; 
              sleep 1; 
            done;

  backoffLimit: 0          