kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes  1;

    error_log  /var/log/error.log warn;
    pid        /var/run/nginx.pid;
    
    events {
      worker_connections  4096;
    }
    
    http {
      client_max_body_size 200m;
      
      include       mime.types;
      default_type  application/octet-stream;
  
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
      '$status $body_bytes_sent "$http_referer" '
      '"$http_user_agent" "$http_x_forwarded_for"';
  
      access_log off;
  
      sendfile        on;
  
      keepalive_timeout  65;
  
      server {
        listen 0.0.0.0:8000;

        root /app/public;

        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Fingerprint,Custom-Auth';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
        add_header 'Access-Control-Allow-Credentials' 'true';

        location / {
          try_files $uri @rewriteapp;
        }

        location @rewriteapp {
          # rewrite all to app.php
          rewrite ^(.*)$ /index.php/$1 last;
        }

        location ~ ^/(index|app_dev|config)\.php(/|$) {
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_split_path_info ^(.+\.php)(/.*)$;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param HTTPS off;
        }
      }
    }