apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 6 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 8 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 10 }}
    spec:
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config    
      containers:
        - image: avernusx/otus-homework-2-php-fpm:latest
          name: php-fpm
          env:
            - name: DB_USER
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: DB_PASS
              value: {{ .Values.postgresql.postgresqlPassword }}
            - name: DB_NAME
              value: {{ .Values.postgresql.postgresqlDatabase }}
            - name: DB_HOST
              value: {{ include "postgresql.fullname" . }}
            - name: DB_PORT
              value: {{ .Values.postgresql.service.port | quote }}
        - image: openresty/openresty:xenial
          name: nginx
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /usr/local/openresty/nginx/conf/nginx.conf
              subPath: nginx.conf
