apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: entrypoint
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: /otusapp/vlaznev($|/)(.*)
          pathType: Prefix
          backend:
            service:
              name: {{ include "app.fullname" . }}
              port:
                number: 8000