apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "app.labels" . | nindent 4 }}
  name: {{ include "app.fullname" . }}
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
      name: web
  selector:
    {{- include "app.selectorLabels" . | nindent 6 }}
  type: NodePort